### ISSUE TITLE
Stuck on Download API screen

### ISSUE THREAD

**Issue by coolgem923** [dannysmc95/DiscoverAPI#2]
![2015-11-11_20 42 33](https://cloud.githubusercontent.com/assets/5619845/11109305/d3584466-88b4-11e5-8f75-98b3582b0e41.png)

**Comment by dannysmc95** [comment]
Did you manually download the new version? as I switched web hosts to a dedicated server, so you will need to manually download the updated version, can be done by running the following:
```pastebin get b4GwKPpU store```

**Comment by dannysmc95** [comment]
Please also note we have a new git server to host all my own programs, you can find it here: http://git.dannysmc.com/ - it is free to signup!
